# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               pseudoaj
tagline:             ''
description:         'Developer. Crawler. Happy Soul.'
url:                 http://pseudoaj.com
baseurl:             ''
plugins:             [jekyll-paginate]
paginate:            5
paginate_path:       'page:num'

# About/contact
author:
  name:              Ajay Kavuri
  url:               https://pseudoaj.com
  email:             ajkavuri@mix.wvu.edu

# Custom vars
version:             1.0.1
